language: python

install:
    - wget https://github.com/gohugoio/hugo/releases/download/v0.45.1/hugo_0.45.1_Linux-64bit.deb
    - sudo dpkg -i hugo*.deb

script:
    - hugo -t hugo-sustain

after_success: |
    if [ -n "$GITHUB_API_KEY" ]; then
      ## Init
      git submodule add -b master https://github.com/mehdibaha/mehdibaha.github.io public
      cd public
      git add -f --ignore-errors --all
      ## Deploy
      msg="rebuilding site `date`"
      if [ $# -eq 1 ]
        then msg="$1"
      fi
      git -c user.name='travis' -c user.email='travis' commit -m "$msg"
      git push -f -q https://$GITHUB_USER:$GITHUB_API_KEY@github.com/$TRAVIS_REPO_SLUG master
    fi
