language: python

install:
    - wget https://github.com/gohugoio/hugo/releases/download/v0.45.1/hugo_0.45.1_Linux-64bit.deb
    - sudo dpkg -i hugo*.deb

script:
    - hugo

after_success: |
    - git submodule add -b https://$GITHUB_USER:$GITHUB_API_KEY@github.com/$DEPLOYMENT_REPO.git public
    - cd public && git add -f --ignore-errors --all
    - git -c user.name='Deployment Bot' -c user.email='deploy@travis-ci.org' commit -m "$TRAVIS_COMMIT_MESSAGE"
    - git push -f -q https://$GITHUB_USER:$GITHUB_API_KEY@github.com/$DEPLOYMENT_REPO master
